export const QUERY_KEY = {
  GET_EXAMPLES: "GET_EXAMPLES",
  GET_EXAMPLE: "GET_EXAMPLE",
  GET_PRODUCT_LIST: "GET_PRODUCT_LIST",
  GET_PRODUCT_DETAILS: "GET_PRODUCT_DETAILS",
  GET_CART_LIST: "GET_CART_LIST",
};
